name: cash_track
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  firebase_auth: ^5.3.0
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: RubikOne
      fonts:
        - asset: assets/fonts/RubikOne-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_ct.png"

flutter_native_splash:
  color: "#CECECE"
  branding_mode: bottom
  branding_bottom_padding: 300
  branding: assets/icons/app_icon_ct_default.png
